// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjhdlzuhwtkmkiaifshh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqaGRsenVod3RrbWtpYWlmc2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Njg3NzQsImV4cCI6MjA2MjA0NDc3NH0.2hAB4rH98DOOe21DszaSBGjnr1uCPH5tXrTfQI-vyg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);